# Generated by Django 5.0.14 on 2025-11-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='requestapprovallevel',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestapprovallevel',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='procurement.purchaserequest'),
        ),
        migrations.AddField(
            model_name='requestapprovallevel',
            name='role',
            field=models.ForeignKey(help_text='Role required to approve this level', on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequest'),
        ),
        migrations.AlterUniqueTogether(
            name='requestapprovallevel',
            unique_together={('request', 'level')},
        ),
    ]
