# Generated by Django 5.0.14 on 2025-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='extracted_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_data',
            field=models.JSONField(blank=True, help_text='Extracted data from proforma document', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_data',
            field=models.JSONField(blank=True, help_text='Extracted data from receipt document', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='validation_result',
            field=models.JSONField(blank=True, help_text='Receipt validation results against PO', null=True),
        ),
    ]
