# Generated by Django 5.0.14 on 2025-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_extracted_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
