# Generated by Django 5.0.14 on 2025-11-26 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('procurement', '0004_alter_purchaserequest_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum amount for this configuration (inclusive)', max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount for this configuration (inclusive). Leave blank for unlimited.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approval Configuration',
                'verbose_name_plural': 'Approval Configurations',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalConfigLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(help_text='Approval level number (1, 2, 3, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='procurement.approvalconfig')),
                ('group', models.ForeignKey(help_text='Group required to approve this level', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Approval Configuration Level',
                'verbose_name_plural': 'Approval Configuration Levels',
                'ordering': ['config', 'level'],
                'unique_together': {('config', 'level')},
            },
        ),
    ]
